// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { supabaseDefaults } from '@/config';

// 환경 변수가 있으면 사용, 없으면 config 기본값 사용 (Lovable에서 별도 설정 불필요)
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || supabaseDefaults.url;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || supabaseDefaults.anonKey;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});